### ISSUE TITLE
Files are not automatically created inside the chosen dirname defined in fronmatter.json

### ISSUE THREAD

**Issue by 1sma31L** [condorheroblog/auto-front-matter#2]
when i `Ctrl+Shift+P` and run the command and chose the file name it is not creating files inside of the chose dirname.
I have created a pull request which i kindly ask for the  author to review or test.

**Comment by condorheroblog** [comment]
Thank you for reporting this issue.

The dirname option may be an array. I think the best strategy at present is to put the newly created files in the root directory.
