### ISSUE TITLE
newFileIsInsertLastMod & newFileIsInsertReadTime don't seem to work with uncommitted files

### ISSUE THREAD

**Issue by 1sma31L** [condorheroblog/auto-front-matter#3]
When creating a new .md file and setting
```js
{
    "newFileIsInsertLastMod": true,
    "newFileIsInsertReadTime": true
}
```
inside frontmatter.json and saving the uncommited file, the lastMod dosnt refresh to the current time nor does duration to reading time.

**Comment by condorheroblog** [comment]
Please install v5.0.0.
