### ISSUE TITLE
Extension crashing when running the command auto-front-matter.createMdFromTemplate 

### ISSUE THREAD

**Issue by 1sma31L** [condorheroblog/auto-front-matter#4]
can't create new .md files in the new update
![Screenshot from 2024-09-08 20-06-56](https://github.com/user-attachments/assets/a2d700d8-48d2-49a5-bc09-c6cb4c8c51cb)
I have frontmatter.json configured, Which worked fine with the prev version.
vscode version: 1.93.0-1

**Comment by condorheroblog** [comment]
Please use version v6
