### ISSUE TITLE
Custom template with current date

### ISSUE THREAD

**Issue by mahdi739** [condorheroblog/auto-front-matter#5]
Hi. Thank you for your helpful project.

How can we define a custom template while keeping the current date field, which should be generated with a JavaScript function?

**Comment by condorheroblog** [comment]
You can use `"{{now}}"` in `frontmatter.json` file:

```json
{
  "template": {
    "data": {
      "date": "{{now}}",
      "author": "CondorHero",
      "tags": [
        "hello",
        "world"
      ],
      "categories": "blog"
    },
    "content": "\n# Hello World!\n"
  }
}
```

And there are three other template variants: `"{{year}}"`, `"{{month}}"`, `"{{day}}"`.


I wrote this project very early, and I have to say that the documentation is really bad.😂
